apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-viewer
  namespace: os-basic-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab-resource-reader
  namespace: os-basic-lab
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lab-resource-reader
  namespace: os-basic-lab
subjects:
  - kind: ServiceAccount
    name: lab-viewer
    namespace: os-basic-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lab-resource-reader
