apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: os-basic-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-readiness-evidence
    environment: training-only
  annotations:
    openshift.io/description: OpenShift basic resources training only
    openshift.io/display-name: OpenShift Basic Lab
