apiVersion: v1
kind: ResourceQuota
metadata:
  name: workload-quota
  namespace: example-web-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
    count/routes.route.openshift.io: "5"
    persistentvolumeclaims: "2"

